var fix = [
  {country: 'Vietnam', find: 'Hcm', replace: 'Ho Chi Minh'},
  {country: 'Vietnam', find: 'Ho Chi Minh City', replace: 'Ho Chi Minh'},
  {country:'United Kingdom', find:'London', replace:'London'},
  {country:'United Kingdom', find:'london', replace:'London'},
  {country:'Italy', find:'Rome', replace:'Roma'},
  {country:'Italy', find:'Italy', replace:'Roma'},
  {country:'Italy', find:'Milan', replace:'Milano'},
  {country:'Italy', find:'Milani', replace:'Milano'},
  {country:'United States', find:'Nyc', replace:'New York'},
  {country:'United States', find:'New york', replace:'New York'},
  {country:'United States', find:'new york', replace:'New York'},
  {country:'United States', find:'newyork', replace:'New York'},
  {country:'United States', find:'Newyork', replace:'New York'},
  {country:'United States', find:'New York, Ny 10003', replace:'New York'},
  {country:'United States', find:'New York, NY 10025', replace:'New York'},
  {country:'United States', find:'New York,', replace:'New York'},
  {country:'United States', find:'NEW YORK', replace:'New York'},
  {country:'United States', find:'Newyok', replace:'New York'},
  {country:'United States', find:'New York City', replace:'New York'},
  {country:'United States', find:'New York, Ny', replace:'New York'},
  {country:'United States', find:'New York,', replace:'New York'},
  {country:'United States', find:'New York, Ny 10025', replace:'New York'},
  {country:'United States', find:'New York, Ny 10003', replace:'New York'},
  {country:'Russia', find:'moscow', replace:'Moscow'},
  {country:'Russia', find:'Moscow', replace:'Moscow'},
  {country:'Russia', find:'Moscow Region', replace:'Moscow'},
  {country:'Russia', find:'Moscow ', replace:'Moscow'},
  {country:'Mexico', find:'mexico', replace:'Mexico City'},
  {country:'Mexico', find:'Mexico City', replace:'Mexico City'},
  {country:'Mexico', find:'distrito federal', replace:'Mexico City'},
  {country:'Mexico', find:'DF', replace:'Mexico City'},
  {country:'Mexico', find:'Ciudad de Mu00e9xico', replace:'Mexico City'},
  {country:'Mexico', find:'México City ', replace:'Mexico City'},
  {country:'Mexico', find:'Mexico', replace:'Mexico City'},
  {country:'Mexico', find:'Mexico D.f.', replace:'Mexico City'},
  {country:'Mexico', find:'Mexico, Df', replace:'Mexico City'},
  {country:'Mexico', find:'Cdmx', replace:'Mexico City'},
  {country:'Mexico', find:'C.d.m,x', replace:'Mexico City'},
  {country:'Mexico', find:'Df', replace:'Mexico City'},
  {country:'Mexico', find:'Emxico', replace:'Mexico City'},
  {country:'Mexico', find:'México', replace:'Mexico City'},
  {country:'Mexico', find:'México D.f ', replace:'Mexico City'},
  {country:'Mexico', find:'México D.f', replace:'Mexico City'},
  {country:'Mexico', find:'Mexico Df', replace:'Mexico City'},
  {country:'Mexico', find:'Mex', replace:'Mexico City'},
  {country:'Mexico', find:'Mx', replace:'Mexico City'},
  {country:'Mexico', find:'Ciudad De México', replace:'Mexico City'},
  {country:'Mexico', find:'Cd. De México', replace:'Mexico City'},
  {country:'Mexico', find:'Distrito Federal', replace:'Mexico City'},
  {country:'Mexico', find:'D.f', replace:'Mexico City'},
  {country:'Mexico', find:'D.f.', replace:'Mexico City'},
  {country:'Mexico', find:'México City', replace:'Mexico City'},
  {country:'Mexico', find:'México Df', replace:'Mexico City'},
  {country:'Mexico', find:'Ciudad De Mex', replace:'Mexico City'},
  {country:'Mexico', find:'Ciudad De Mxico', replace:'Mexico City'},
  {country:'Mexico', find:'Mexico Distrito Federal', replace:'Mexico City'},
  {country:'Mexico', find:'Mexico   City', replace:'Mexico City'},
  {country:'Mexico', find:'Mecico City', replace:'Mexico City'},
  {country:'Mexico', find:'Mexicodf', replace:'Mexico City'},
  {country:'Mexico', find:'México D.f.', replace:'Mexico City'},
  {country:'Mexico', find:'México, Df', replace:'Mexico City'},
  {country:'Mexico', find:'México.', replace:'Mexico City'},
  {country:'Mexico', find:'Xalapa,ver', replace:'Xalapa'},
  {country:'Mexico', find:'Xalapa,ver.', replace:'Xalapa'},
  {country:'Mexico', find:'Xalapa, Ver.', replace:'Xalapa'},
  {country:'Mexico', find:'Xalapa, Ver', replace:'Xalapa'},
  {country:'Brazil', find:'San Paolo', replace:'Sao Paolo'},
  {country:'Hong Kong', find:'hk', replace:'Hong Kong'},
  {country:'Hong Kong', find:'Hk', replace:'Hong Kong'},
  {country:'Hong Kong', find:'hK', replace:'Hong Kong'},
  {country:'Hong Kong', find:'HK', replace:'Hong Kong'},
  {country:'Hong Kong', find:'hongkong', replace:'Hong Kong'},
  {country:'Hong Kong', find:'Hongkong', replace:'Hong Kong'},
  {country:'Hong Kong', find:'HongKong', replace:'Hong Kong'},
  {country:'Poland', find:'#322;upsk', replace:'Słupsk'},
  {country:'Taiwan', find:'#39640;&amp;#38596;&amp;#24066;', replace:'高雄市'},
  {country:'Italy', find:' di Castello', replace:'Città di Castello'},
  {country:'Italy', find:'#146; di csatello', replace:'Città di Castello'},
  {country:'Italy', find:'#146; Di Csatello', replace:'Città di Castello'},
  {country:'Italy', find:' Di Csatello', replace:'Città di Castello'},
  {country:'Italy', find:' di piave', replace:'San Donà di Piave'},
  {country:'Italy', find:' Di Piave', replace:'San Donà di Piave'},
  {country:'Italy', find:'#146;adda', replace:"Trezzo sull'Adda"},
  {country:'Iceland', find:'#146;alessio siculo', replace:"Sant'Alessio Siculo"},
  {country:'Italy', find:"#146;aquila", replace:"L'Aquila"},
  {country:'Italy', find:'#146;Aquila', replace:"L'Aquila"},
  {country:'Italy', find:'#146;Elpidio', replace:"Porto Sant'Elpidio"},
  {country:'Italy', find:'#146;elpidio', replace:"Porto Sant'Elpidio"},
  {country:'Italy', find:'#8217;ilario d’enza (RE)', replace:"Sant'Ilario d'Enza"},
  {country:'Italy', find:'#8217;ilario D&#8217;enza (Re)', replace:"Sant'Ilario d'Enza"},
  {country:'United States', find:'(Sf) Bay Area', replace:"San Francisco"},
  {country:'Poland', find:'#322;awiec', replace:"Bolesławiec"},
  {country:'Italy', find:'-Napoli', replace:"Napoli"},
  {country: 'Latvia', find: 'Russia - Mosca', replace: 'Moskva'},
  {country: 'Italy', find: '#146;arco', replace: 'Arco'},
  {country: 'Italy', find: '#146;artico', replace: 'Padulle'},
  {country: 'Italy', find: '#146;ete', replace: 'More Corraxe'},
  {country: 'Germany', find: 'A', replace: 'San Jose'},
  {country: 'Mexico', find: 'A', replace: 'Mexico City'},
  {country: 'France', find: 'Aa', replace: 'Paris'},
  {country: 'Finland', find: 'Aberdee', replace: 'Helsinki'},
  {country: 'United States', find: 'Ad', replace: 'Detroit'},
  {country: 'United Kingdom', find: 'Adasd', replace: 'Bradley Stoke'},
  {country: 'Germany', find: 'Adasdas', replace: 'Berlin'},
  {country: 'United States', find: 'Alta Loma', replace: 'Rancho Cucamonga'},
  {country: 'Israel', find: 'Amsterdam', replace: 'Petah Tikva'},
  {country: 'Ireland', find: 'Amsterdam', replace: 'Fort Johnson'},
  {country: 'Germany', find: 'Ast', replace: 'Waldmünchen'},
  {country: 'India', find: 'Az', replace: 'Tempe'},
  {country: 'Guatemala', find: 'Barcelona', replace: 'Guatemala'},
  {country: 'Germany', find: 'Barcelona', replace: 'Köln'},
  {country: 'India', find: 'Bdn', replace: 'Nagpur'},
  {country: 'Germany', find: 'Bdng', replace: 'Köln'},
  {country: 'Russia', find: 'Be', replace: 'Are'},
  {country: 'Ireland', find: 'Berlin', replace: 'Tramore'},
  {country: 'Israel', find: 'Berlin', replace: 'Netanya'},
  {country: 'United States', find: 'Chugiak', replace: 'Anchorage'},
  {country: 'Guatemala', find: 'China', replace: 'Guatemala'},
  {country: 'United States', find: 'Chatsworth', replace: 'Los Angeles'},
  {country: 'France', find: 'Bzh', replace: 'Marolles'},
  {country: 'Denmark', find: 'Brønshøj', replace: 'Copenhagen'},
  {country: 'France', find: 'Borde', replace: 'Saugues'},
  {country: 'Germany', find: 'Beucha', replace: 'Brandis'},
  {country: 'France', find: 'Beyond', replace: 'Stratton'},
  {country: 'Germany', find: 'Bi', replace: 'Ingelheim am Rhein'},
  {country: 'Germany', find: 'Blubb', replace: 'Berlin'},
  {country: 'Greece', find: 'Braxami', replace: 'Agios Dimitrios'},
  {country: 'Bosnia and Herzegovina', find: 'Brest', replace: 'Zaugline'},
  {country: 'France', find: 'Bsm', replace: 'Rennes'},
  {country: 'Germany', find: 'C-r', replace: 'Duisburg'},
  {country: 'United States', find: 'Canyon Country', replace: 'Santa Clarita'},
  {country: 'United States', find: 'Chitown', replace: 'Chicago'},
  {country: 'Tuvalu', find: 'City', replace: 'Tuval'},
  {country: 'Tonga', find: 'City', replace: 'Tonga'},
  {country: 'United Arab Emirates', find: 'City', replace: 'Los Angeles'},
  {country: 'United States', find: 'Cityplace', replace: 'West Palm Beach'},
  {country: 'Germany', find: 'Ck', replace: 'Osnabrück'},
  {country: 'Germany', find: 'Dewed', replace: 'Bremen'},
  {country: 'United States', find: 'Dfg', replace: 'Washington'},
  {country: 'United Arab Emirates', find: 'Diera City', replace: 'Dubai'},
  {country: 'Germany', find: 'Diestqdt', replace: 'Weil der Stadt'},
  {country: 'Spain', find: 'Dinamarca', replace: 'Oviedo'},
  {country: 'Spain', find: 'Dj', replace: 'Estepona'},
  {country: 'Germany', find: 'Dle', replace: 'Delmenhorst'},
  {country: 'Germany', find: 'Daran', replace: 'Berlin'},
  {country: 'United States', find: 'Davenport, Ia', replace: 'Davenport'},
  {country: 'Thailand', find: 'Dc', replace: 'Washington'},
  {country: 'United Kingdom', find: 'Cuba', replace: 'Havana'},
  {country: 'United States', find: 'Chugiak', replace: 'Anchorage'},
  {country: 'Guatemala', find: 'China', replace: 'Guatemala'},
  {country: 'United States', find: 'Chatsworth', replace: 'Los Angeles'},
  {country: 'France', find: 'Bzh', replace: 'Marolles'},
  {country: 'Denmark', find: 'Brønshøj', replace: 'Copenhagen'},
  {country: 'France', find: 'Borde', replace: 'Saugues'},
  {country: 'Germany', find: 'Beucha', replace: 'Brandis'},
  {country: 'France', find: 'Beyond', replace: 'Stratton'},
  {country: 'Germany', find: 'Bi', replace: 'Ingelheim am Rhein'},
  {country: 'Germany', find: 'Blubb', replace: 'Berlin'},
  {country: 'Greece', find: 'Braxami', replace: 'Agios Dimitrios'},
  {country: 'Bosnia and Herzegovina', find: 'Brest', replace: 'Zaugline'},
  {country: 'France', find: 'Bsm', replace: 'Rennes'},
  {country: 'Germany', find: 'C-r', replace: 'Duisburg'},
  {country: 'United States', find: 'Canyon Country', replace: 'Santa Clarita'},
  {country: 'United States', find: 'Chitown', replace: 'Chicago'},
  {country: 'Tuvalu', find: 'City', replace: 'Tuval'},
  {country: 'Tonga', find: 'City', replace: 'Tonga'},
  {country: 'United Arab Emirates', find: 'City', replace: 'Los Angeles'},
  {country: 'United States', find: 'Cityplace', replace: 'West Palm Beach'},
  {country: 'Germany', find: 'Ck', replace: 'Osnabrück'},
  {country: 'United States', find: 'Dc', replace: 'Washington'},
  {country: 'France', find: 'Fd', replace: 'Tiffin'},
  {country: 'France', find: 'Fdf', replace: 'Le Lamentin'},
  {country: 'United States', find: 'Fg', replace: 'Stowe Township'},
  {country: 'Germany', find: 'Ficken', replace: 'Berlin'},
  {country: 'United States', find: 'Fc', replace: 'Chicago'},
  {country: 'India', find: 'Esfhan', replace: 'Kalyan'},
  {country: 'Germany', find: 'Esa', replace: 'Eisenach'},
  {country: 'United States', find: 'Enterprise', replace: 'Independence'},
  {country: 'France', find: 'Enderson', replace: 'Pendleton'},
  {country: 'France', find: 'Ee', replace: 'Bobigny'},
  {country: 'Spain', find: 'Eaf', replace: 'Madrid'},
  {country: 'France', find: 'Drag', replace: 'Colmar'},
  {country: 'Spain', find: 'Donosti', replace: 'San Sebastián'},
  {country: 'Spain', find: 'Donostia', replace: 'San Sebastián'},
  {country: 'United States', find: 'Dorchester, Ma', replace: 'Boston'},
  {country: 'Germany', find: 'G.', replace: 'Gera'},
  {country: 'Georgia', find: 'Gdl', replace: 'Fayetteville'},
  {country: 'Germany', find: 'God', replace: 'Elliottsburg'},
  {country: 'Germany', find: 'Graupa', replace: 'Pirna'},
  {country: 'United States', find: 'Grayscale', replace: 'Murphysboro'},
  {country: 'Germany', find: 'Greenberg', replace: 'Berlin'},
  {country: 'Germany', find: 'Gtown', replace: 'Washington'},
  {country: 'Georgia', find: 'Halle', replace: 'Atlanta'},
  {country: 'United States', find: 'Harvard', replace: 'Cambridge'},
  {country: 'France', find: 'Hellemmes', replace: 'Lille'},
  {country: 'British Virgin Islands', find: 'Here', replace: 'Road Town'},
  {country: 'United States', find: 'Here', replace: 'Atlanta'},
  {country: 'United States', find: 'Hollydale', replace: 'South Gate'},
  {country: 'Germany', find: 'Hometown', replace: 'Göttingen'},
  {country: 'Germany', find: 'Hro', replace: 'Rostock'},
  {country: 'Germany', find: 'Htown', replace: 'Bonn'},
  {country: 'France', find: 'Hugh', replace: 'New Market'},
  {country: 'Uganda', find: 'Iceland', replace: 'Kampala'},
  {country: 'United States', find: 'Jazz', replace: 'Kansas City'},
  {country: 'France', find: 'Juju', replace: 'Toulouse'},
  {country: 'Germany', find: 'Kingstone', replace: 'Köln'},
  {country: 'Iceland', find: 'La', replace: 'Los Angeles'},
  {country: 'Germany', find: 'Leipzig-sax', replace: 'Schkeuditz'},
  {country: 'Bangladesh', find: 'Leverga', replace: 'Dhaka'},
  {country: 'Tanzania', find: 'Lifr', replace: 'Dar es Salaam'},
  {country: 'France', find: 'London', replace: 'Savigny-sur-Seille'},
  {country: 'Sweden', find: 'London', replace: 'Gothenburg'},
  {country: 'Australia', find: 'London', replace: 'Sundown'},
  {country: 'Argentina', find: 'London', replace: 'Guadalupe'},
  {country: 'Andorra', find: 'London', replace: 'Andorra la Vella'},
  {country: 'Austria', find: 'Lten', replace: 'Wien'},
  {country: 'Germany', find: 'Lu', replace: 'Lech'},
  {country: 'Spain', find: 'Mali', replace: 'Xàbia'},
  {country: 'France', find: 'Marbella', replace: 'Paris'},
  {country: 'Norway', find: 'Mexico City', replace: 'Ciudad de México'},
  {country: 'Greece', find: 'Milan', replace: 'Ferno'},
  {country: 'Australia', find: 'Milan', replace: 'Pier Milan'},
  {country: 'Switzerland', find: 'Min', replace: 'Yens'},
  {country: 'Germany', find: 'Mmmmm', replace: 'Planegg'},
  {country: 'Germany', find: 'Mod', replace: 'Erfurt'},
  {country: 'Switzerland', find: 'Monte', replace: 'Castel San Pietro'},
  {country: 'Afghanistan', find: 'Moscow', replace: 'Moskva'},
  {country: 'Australia', find: 'Moscow', replace: 'Moskva'},
  {country: 'Germany', find: 'Mu', replace: 'Munich'},
  {country: 'Spain', find: 'Mu', replace: 'Columbia'},
  {country: 'Germany', find: 'Musterstadt', replace: 'Berlin'},
  {country: 'Germany', find: 'Mutzschen', replace: 'Grimma'},
  {country: 'India', find: 'Napoli', replace: 'San Diego'},
  {country: 'Armenia', find: 'New York', replace: 'Yerevan'},
  {country: 'China', find: 'New York', replace: 'Oak Ridge'},
  {country: 'Argentina', find: 'New York', replace: 'Haedo'},
  {country: 'Poland', find: 'New York', replace: 'Poland'},
  {country: 'Albania', find: 'New York', replace: 'Tiranë'},
  {country: 'Angola', find: 'New York', replace: 'Angola'},
  {country: 'Suriname', find: 'New York', replace: 'Paramaribo'},
  {country: 'American Samoa', find: 'New York, Ny 10003', replace: 'New York'},
  {country: 'Belize', find: 'Newyork', replace: 'New York'},
  {country: 'United Kingdom', find: 'Newyork', replace: 'New York'},
  {country: 'Australia', find: 'Newyork', replace: 'New York'},
  {country: 'Albania', find: 'Newyork', replace: 'New York'},
  {country: 'Antigua and Barbuda', find: 'Newyork', replace: 'New York'},
  {country: 'American Samoa', find: 'Newyork', replace: 'New York'},
  {country: 'Algeria', find: 'Newyork', replace: 'Chekfa'},
  {country: 'Angola', find: 'Newyork', replace: 'Angola'},
  {country: 'Andorra', find: 'Newyork', replace: 'New York'},
  {country: 'Argentina', find: 'Newyork', replace: 'Haedo'},
  {country: 'Ukraine', find: 'Nikolaev', replace: 'Mykolaiv'},
  {country: 'United Kingdom', find: 'Nirmingham', replace: 'Birmingham'},
  {country: 'Hungary', find: 'Nk', replace: 'Debrecen'},
  {country: 'France', find: 'Nn', replace: 'Isigny-le-Buat'},
  {country: 'Germany', find: 'No Need', replace: 'Berlin'},
  {country: 'Germany', find: 'None', replace: 'Oakland'},
  {country: 'Hungary', find: 'None', replace: 'Budapest'},
  {country: 'Germany', find: 'Nt', replace: 'Osnabrück'},
  {country: 'Grenada', find: 'Of Angles', replace: 'Los Angeles'},
  {country: 'France', find: 'Ontheroadagain', replace: 'Nozay'},
  {country: 'France', find: 'Paname', replace: 'Paris'},
  {country: 'Turkey', find: 'Paris', replace: 'Orlando'},
  {country: 'French Guiana', find: 'Paris', replace: 'Kourou'},
  {country: 'Ukraine', find: 'Paris', replace: 'Veselyi Kut'},
  {country: 'Georgia', find: 'Passau', replace: 'Ering'},
  {country: 'Germany', find: 'Peans', replace: 'Aachen'},
  {country: 'Glendale, Arizona', find: 'Phoenix', replace: 'Glendale'},
  {country: 'France', find: 'Plo', replace: 'Arthès'},
  {country: 'Bosnia and Herzegovina', find: 'Rajvosa', replace: 'Sarajevo'},
  {country: 'Germany', find: 'Rde', replace: 'Pulheim'},
  {country: 'Spain', find: 'Renteria', replace: 'Errenteria'},
  {country: 'Switzerland', find: 'Rich', replace: 'Ansted'},
  {country: 'Uganda', find: 'Roma', replace: 'Kampala'},
  {country: 'Italy', find: 'Roma Barcelona', replace: 'Barcellona Pozzo di Gotto'},
  {country: 'Honduras', find: 'Rome', replace: 'Roma'},
  {country: 'Germany', find: 'Rome', replace: 'Berlin'},
  {country: 'Afghanistan', find: 'Rome', replace: 'Roma'},
  {country: 'Iceland', find: 'Roms', replace: 'Roma'},
  {country: 'Germany', find: 'Ruhrgebiet', replace: 'Mülheim'},
  {country: 'France', find: 'Saint A Pitre', replace: 'Miremont'},
  {country: 'Germany', find: 'Samanyolu', replace: 'Berlin'},
  {country: 'France', find: '5350', replace: 'Molines-en-Queyras'},
  {country: 'United States', find: '9134', replace: 'Eden'},
  {country: 'United States', find: '111 North Delancy Place', replace: 'Atlantic City'},
  {country: 'Gabon Republic', find: '123', replace: 'Libreville'},
  {country: 'United States', find: '19103', replace: 'Philadelphia'},
  {country: 'Germany', find: '39590', replace: 'Storkau'},
  {country: 'Germany', find: '48485 Neuenkirchen', replace: 'Neuenkirchen'},
  {country: 'Germany', find: '55131', replace: 'Mainz'},
  {country: 'Germany', find: '60487 Frankfurt', replace: 'Frankfurt'},
  {country: 'Germany', find: '65618', replace: 'Selters'},
  {country: 'Germany', find: '71665', replace: 'Vaihingen an der Enz'},
  {country: 'Switzerland', find: '8004 Zürich', replace: 'Zürich'},
  {country: 'Portugal', find: 'A Da Palmeira', replace: 'Palmeira'},
  {country: 'Chile', find: 'A Del Mar', replace: 'Viña del Mar'},
  {country: 'United Arab Emirates', find: 'Abu Dhabi - Al-ain', replace: 'Al Ain'},
  {country: 'United Arab Emirates', find: 'Abudabi', replace: 'Abu Dhabi'},
  {country: 'United Arab Emirates', find: 'Abudhabi', replace: 'Abu Dhabi'},
  {country: 'Israel', find: 'Acco', replace: 'Acre'},
  {country: 'Greece', find: 'Agia Paraskeyi', replace: 'Agia Paraskevi'},
  {country: 'Hungary', find: 'Agykovacsi', replace: 'Nagykovácsi'},
  {country: 'France', find: 'Aix En Provence', replace: 'Aix-en-Provence'},
  {country: 'Germany', find: 'Ajrensburg', replace: 'Ahrensburg'},
  {country: 'Israel', find: 'Akko', replace: 'Acre'},
  {country: 'United Arab Emirates', find: 'Al-ain', replace: 'Al Ain'},
  {country: 'France', find: 'Ales', replace: 'Alès'},
  {country: 'Hungary', find: 'Algyo', replace: 'Algyő'},
  {country: 'France', find: 'Andresy', replace: 'Andrésy'},
  {country: 'France', find: 'Angers / Sens', replace: 'Angers'},
  {country: 'France', find: 'Angouleme', replace: 'Angoulême'},
  {country: 'Italy', find: 'Areggio', replace: 'Viareggio'},
  {country: 'France', find: 'Argeles Sur Mer', replace: 'Argelès-sur-Mer'},
  {country: 'France', find: 'Asnieres', replace: 'Asnières-sur-Seine'},
  {country: 'France', find: 'Asnières', replace: 'Asnières-sur-Seine'},
  {country: 'United States', find: 'Atl', replace: 'Atlanta'},
  {country: 'Germany', find: 'Auerbach/vogtl.', replace: 'Auerbach'},
  {country: 'France', find: 'Auvers Sur Oise', replace: 'Auvers-sur-Oise'},
  {country: 'France', find: 'Aux', replace: 'Aix-en-Provence'},
  {country: 'France', find: 'Auxi Le Chateau', replace: 'Auxi-le-Château'},
  {country: 'Ukraine', find: 'Bachmach', replace: 'Bakhmach'},
  {country: 'United States', find: 'Bakersfeild', replace: 'Bakersfield'},
  {country: 'United States', find: 'Baldwinville', replace: 'Templeton'},
  {country: 'India', find: 'Bangalore', replace: 'Bengaluru'},
  {country: 'India', find: 'Banglore', replace: 'Bengaluru'},
  {country: 'United Kingdom', find: 'Barrow In Furness', replace: 'Barrow-in-Furness'},
  {country: 'United States', find: 'Basking Ridge', replace: 'Bernards'},
  {country: 'Switzerland', find: 'Basle', replace: 'Basel'},
  {country: 'Indonesia', find: 'Bdg', replace: 'Bandung'},
  {country: 'France', find: 'Bdx', replace: 'Blanquefort'},
  {country: 'Germany', find: 'Beck', replace: 'Beckum'},
  {country: 'Israel', find: 'Beer Seva', replace: "Be'er Sheva"},
  {country: 'Israel', find: 'Beer Sheva', replace: "Be'er Sheva"},
  {country: 'France', find: 'Beire Le Chatel', replace: 'Beire-le-Châtel'},
  {country: 'United States', find: 'Bellefontaine Oh', replace: 'Bellefontaine'},
  {country: 'Italy', find: 'Bergamo Roma', replace: 'Bergamo'},
  {country: 'Germany', find: 'Berlin', replace: 'Berlin'},
  {country: 'Germany', find: 'Berlun', replace: 'Berlin'},
  {country: 'Germany', find: 'Bernau', replace: 'Bernau bei Berlin'},
  {country: 'Switzerland', find: 'Berne', replace: 'Bern'},
  {country: 'United States', find: 'Beverlyhills', replace: 'Beverly Hills'},
  {country: 'Bosnia and Herzegovina', find: 'Bihac', replace: 'Bihać'},
  {country: 'United Kingdom', find: 'Birm', replace: 'Birmingham'},
  {country: 'Germany', find: 'Bitterfeld', replace: 'Bitterfeld-Wolfen'},
  {country: 'Thailand', find: 'Bkk', replace: 'Bangkok'},
  {country: 'Thailand', find: 'Bkk.', replace: 'Bangkok'},
  {country: 'United States', find: 'Bloomingtown', replace: 'Bloomington'},
  {country: 'Turkey', find: 'Bodrum Mugla', replace: 'Bodrum'},
  {country: 'Switzerland', find: 'Bogno', replace: 'Lugano'},
  {country: 'Poland', find: 'Bolesławiec', replace: 'Boleslawiec'},
  {country: 'Italy', find: 'Bolo', replace: 'Bologna'},
  {country: 'Sweden', find: 'Boras', replace: 'Borås'},
  {country: 'France', find: 'Boulogne-billancourt', replace: 'Boulogne-Billancourt'},
  {country: 'United Kingdom', find: 'Bourenmouth', replace: 'Bournemouth'},
  {country: 'France', find: 'Bourg-en-bresse', replace: 'Bourg-en-Bresse'},
  {country: 'France', find: 'Bourgoin Jallieu', replace: 'Bourgoin-Jallieu'},
  {country: 'Switzerland', find: 'Bouveret', replace: 'Port-Valais'},
  {country: 'Hungaria', find: 'Bp', replace: 'Budapest'},
  {country: 'Hungary', find: 'Bp', replace: 'Budapest'},
  {country: 'Germany', find: 'Braunschweig', replace: 'Brunswick'},
  {country: 'France', find: 'Breau Et Salagosse', replace: 'Bréau-et-Salagosse'},
  {country: 'France', find: 'Breze', replace: 'Brézé'},
  {country: 'Germany', find: 'Bruddelstadt', replace: 'Rudolstadt'},
  {country: 'Germany', find: 'Bruehl', replace: 'Brühl'},
  {country: 'France', find: 'Brussel', replace: 'Brussels'},
  {country: 'Hungary', find: 'Buapest', replace: 'Budapest'},
  {country: 'Hungary', find: 'Bud', replace: 'Budapest'},
  {country: 'Hungary', find: 'Budapesr', replace: 'Budapest'},
  {country: 'Hungary', find: 'Budapesz', replace: 'Budapest'},
  {country: 'Hungary', find: 'Budapset', replace: 'Budapest'},
  {country: 'Hungary', find: 'Budepast', replace: 'Budapest'},
  {country: 'France', find: 'Buis', replace: 'Cour-et-Buis'},
  {country: 'France', find: 'Buis Les Baronnies', replace: 'Buis-les-Baronnies'},
  {country: 'Israel', find: 'Caesaria', replace: 'Caesarea'},
  {country: 'France', find: 'Cagnes Sur Mer', replace: 'Cagnes-sur-Mer'},
  {country: 'Spain', find: 'Carracedo Del Monasterio', replace: 'Carracedo del Monasterio'},
  {country: 'Spain', find: 'Castellon De La Plana', replace: 'Castellón de la Plana'},
  {country: 'Spain', find: 'Castro', replace: 'O Castro'},
  {country: 'France', find: 'Cavalaire', replace: 'Cavalaire-sur-Mer'},
  {country: 'France', find: "Cazouls D'herault", replace: "Cazouls-d'Hérault"},
  {country: 'France', find: 'Cenon Sur Vienne', replace: 'Cenon-sur-Vienne'},
  {country: 'France', find: 'Chalon/saône', replace: 'Chalon-sur-Saône'},
  {country: 'France', find: 'Chambery', replace: 'Chambéry'},
  {country: 'France', find: 'Champs Sur Marne', replace: 'Champs-sur-Marne'},
  {country: 'France', find: 'Charleville', replace: 'Charleville-Mézières'},
  {country: 'United States', find: 'Charlottesville, Va', replace: 'Charlottesville'},
  {country: 'France', find: 'Chateaubriant', replace: 'Châteaubriant'},
  {country: 'France', find: 'Chateauroux', replace: 'Châteauroux'},
  {country: 'France', find: 'Chatellerault', replace: 'Châtellerault'},
  {country: 'France', find: 'Chatyou', replace: 'Chatou'},
  {country: 'United States', find: 'Cherokee,nc', replace: 'Cherokee'},
  {country: 'France', find: 'Chetbourg', replace: 'Cherbourg'},
  {country: 'Thailand', find: 'Chiangmai', replace: 'Chiang Mai'},
  {country: 'Thailand', find: 'Chiangrai', replace: 'Mueang Chiang Rai'},
  {country: 'United States', find: 'Chicago, Il', replace: 'Chicago'},
  {country: 'United States', find: 'Chichago', replace: 'Chicago'},
  {country: 'France', find: 'Choisy', replace: 'Choisy-le-Roi'},
  {country: 'France', find: 'Ch�teauroux', replace: 'Châteauroux'},
  {country: 'United States', find: 'City', replace: 'Kansas City'},
  {country: 'France', find: 'Clermont', replace: 'Clermont-Ferrand'},
  {country: 'France', find: 'Clermont Ferrand', replace: 'Clermont-Ferrand'},
  {country: 'France', find: 'Clermont-ferrand', replace: 'Clermont-Ferrand'},
  {country: 'France', find: 'Clesse', replace: 'Clessé'},
  {country: 'United States', find: 'Colton California', replace: 'Colton'},
  {country: 'United States', find: 'Coluumbia', replace: 'Columbia'},
  {country: 'Denmark', find: 'Copenhagen ø', replace: 'Copenhagen'},
  {country: 'Ireland', find: 'Cor', replace: 'Cork'},
  {country: 'Spain', find: 'Cordoba', replace: 'Córdoba'},
  {country: 'Spain', find: 'Coruña', replace: 'A Coruña'},
  {country: 'France', find: 'Coudequerke', replace: 'Coudekerque-Village'},
  {country: 'France', find: 'Cregy Les Meaux', replace: 'Crégy-lès-Meaux'},
  {country: 'France', find: 'Creteil', replace: 'Créteil'},
  {country: 'Spain', find: 'Cuelllar', replace: 'Cuéllar'},
  {country: 'United States', find: 'Dekalb', replace: 'DeKalb'},
  {country: 'United States', find: 'Delran, Nj', replace: 'Delran'},
  {country: 'Ireland', find: 'Derry', replace: 'Londonderry'},
  {country: 'United States', find: 'Des Moines, Iowa', replace: 'Des Moines'},
  {country: 'United States', find: 'Des Plaines Il.', replace: 'Des Plaines'},
  {country: 'United States', find: 'Desoto', replace: 'DeSoto'},
  {country: 'United States', find: 'Dever', replace: 'Denver'},
  {country: 'Ukraine', find: 'Dnipropetrovsk', replace: 'Dnipro'},
  {country: 'United Kingdom', find: 'Domfries', replace: 'Dumfries'},
  {country: 'Germany', find: 'Dormtund', replace: 'Dortmund'},
  {country: 'France', find: 'Doucy', replace: 'DOUCY COMBELOUVIERE'},
  {country: 'United States', find: 'Downey, California', replace: 'Downey'},
  {country: 'Poland', find: 'Dublin', replace: 'Dubliny'},
  {country: 'Germany', find: 'Duesseldorf', replace: 'Düsseldorf'},
  {country: 'Hungary', find: 'Dunaujvaros', replace: 'Dunaújváros'},
  {country: 'United Kingdom', find: 'Dundeee', replace: 'Dundee'},
  {country: 'France', find: 'Dunkerque', replace: 'Dunkirk'},
  {country: 'United States', find: 'Durahm', replace: 'Durham'},
  {country: 'France', find: 'Durban', replace: 'Durban-Corbières'},
  {country: 'Germany', find: 'Düs', replace: 'Düsseldorf'},
  {country: 'United States', find: 'Eagle Pass Texas', replace: 'Eagle Pass'},
  {country: 'United States', find: 'Eaglecreek', replace: 'Eagle Creek'},
  {country: 'France', find: 'Eauze', replace: 'Éauze'},
  {country: 'France', find: 'Echirolles', replace: 'Échirolles'},
  {country: 'United Kingdom', find: 'Edinbburgh', replace: 'Edinburgh'},
  {country: 'United Kingdom', find: 'Edinburah', replace: 'Edinburgh'},
  {country: 'France', find: 'Elancourt', replace: 'Élancourt'},
  {country: 'Turkey', find: 'Elazig', replace: 'Elâzığ'},
  {country: 'United States', find: 'Ellicott', replace: 'Ellicott City'},
  {country: 'United States', find: 'Ellijay, Ga', replace: 'Ellijay'},
  {country: 'United States', find: 'Elmonte', replace: 'El Monte'},
  {country: 'United States', find: 'Endicott, Ny', replace: 'Endicott'},
  {country: 'Ukraine', find: 'Energodar', replace: 'Enerhodar'},
  {country: 'Spain', find: 'Entregu', replace: 'El Entrego'},
  {country: 'France', find: 'Epernay', replace: 'Épernay'},
  {country: 'France', find: 'Epinay Sur Orge', replace: 'Épinay-sur-Orge'},
  {country: 'Turkey', find: 'Eskisehir', replace: 'Eskişehir'},
  {country: 'France', find: 'Esquize-sere', replace: 'Esquièze-Sère'},
  {country: 'France', find: 'Etables Sur Mer', replace: 'Étables-sur-Mer'},
  {country: 'France', find: 'Etang Salé', replace: 'Etang-Salé les Hauts'},
  {country: 'France', find: 'Etang Salé Les Hauts', replace: 'Etang-Salé les Hauts'},
  {country: 'France', find: 'Etrelles', replace: 'Étrelles'},
  {country: 'France', find: 'Evreux', replace: 'Évreux'},
  {country: 'France', find: 'Eysine', replace: 'Eysines'},
  {country: 'United States', find: 'Fayetteville, Ar', replace: 'Fayetteville'},
  {country: 'United States', find: 'Fort Payne, Al', replace: 'Fort Payne'},
  {country: 'France', find: 'Fort-de-france', replace: 'Fort-de-France Bay'},
  {country: 'Germany', find: 'Frankfurt Am  Main', replace: 'Frankfurt'},
  {country: 'Germany', find: 'Frankfurt Am Main', replace: 'Frankfurt'},
  {country: 'Germany', find: 'Frankfurt/oder', replace: 'Frankfurt an der Oder'},
  {country: 'France', find: 'Frejus', replace: 'Fréjus'},
  {country: 'United States', find: 'Ft Lauderdale', replace: 'Fort Lauderdale'},
  {country: 'United States', find: 'Ft Meade', replace: 'Fort Meade'},
  {country: 'United States', find: 'Ft Wayne', replace: 'Fort Wayne'},
  {country: 'Germany', find: 'Fuerth', replace: 'Fürth'},
  {country: 'United States', find: 'Fullerton, Ca', replace: 'Fullerton'},
  {country: 'United States', find: 'Gardner, Ks', replace: 'Gardner'},
  {country: 'Sweden', find: 'Gbg', replace: 'Gothenburg'},
  {country: 'Switzerland', find: 'Geneve', replace: 'Geneva'},
  {country: 'Spain', find: 'Gernika', replace: 'Guernica'},
  {country: 'Spain', find: 'Gerona', replace: 'Girona'},
  {country: 'Spain', find: 'Gijon', replace: 'Gijón'},
  {country: 'France', find: 'Gimel', replace: 'Gimel-les-Cascades'},
  {country: 'Switzerland', find: 'Ginevra', replace: 'Geneva'},
  {country: 'United States', find: 'Glen Ellyn, Illinois', replace: 'Glen Ellyn'},
  {country: 'United States', find: 'Glenn-dale', replace: 'Glenn Dale'},
  {country: 'Germany', find: 'Goettingen', replace: 'Göttingen'},
  {country: 'United States', find: 'Golab', replace: 'Flower Mound'},
  {country: 'Sweden', find: 'Goteborg', replace: 'Gothenburg'},
  {country: 'Sweden', find: 'Gotheburg', replace: 'Gothenburg'},
  {country: 'Sweden', find: 'Gothenbourg', replace: 'Gothenburg'},
  {country: 'Spain', find: 'Grana', replace: 'Granada'},
  {country: 'United States', find: 'Greater Nashville', replace: 'Nashville'},
  {country: 'United States', find: 'Greenvile', replace: 'Greenville'},
  {country: 'France', find: 'Guerande', replace: 'Guérande'},
  {country: 'Hungary', find: 'Gyor', replace: 'Győr'},
  {country: 'Hungary', find: 'Gyõr', replace: 'Győr'},
  {country: 'Sweden', find: 'Göteborg', replace: 'Gothenburg'},
  {country: 'Guam', find: 'Hagatna', replace: 'Hagåtña'},
  {country: 'United States', find: 'Haiku', replace: 'Haiku-Pauwela'},
  {country: 'Germany', find: 'Hal', replace: 'Halle (Saale)'},
  {country: 'Germany', find: 'Halle', replace: 'Halle (Saale)'},
  {country: 'Germany', find: 'Hann Muenden', replace: 'Hann. Münden'},
  {country: 'Thailand', find: 'Hatyai', replace: 'Hat Yai'},
  {country: 'United States', find: 'Haywrad', replace: 'Hayward'},
  {country: 'Turkey', find: 'Helsinki/istanbul', replace: 'Istanbul'},
  {country: 'France', find: 'Herouville Saint Clair', replace: 'Hérouville-Saint-Clair'},
  {country: 'Germany', find: 'Hh', replace: 'Hollern-Twielenfleth'},
  {country: 'United States', find: 'Housten', replace: 'Houston'},
  {country: 'United States', find: 'Hunstville City', replace: 'Huntsville'},
  {country: 'United States', find: 'Huntsville City', replace: 'Huntsville'},
  {country: 'India', find: 'Hydbd', replace: 'Hyderabad'},
  {country: 'India', find: 'Hyderbad', replace: 'Hyderabad'},
  {country: 'United States', find: 'Indianapolis, In', replace: 'Indianapolis'},
  {country: 'Spain', find: 'Iruña', replace: 'Pamplona'},
  {country: 'France', find: 'Issy', replace: 'Issy-les-Moulineaux'},
  {country: 'France', find: 'Issy Les Moulineaux', replace: 'Issy-les-Moulineaux'},
  {country: 'Ukraine', find: 'Ivano-frankivsk', replace: 'Ivano-Frankivsk'},
  {country: 'Spain', find: 'Jaen', replace: 'Jaén'},
  {country: 'Spain', find: 'Jerez De La Frontera', replace: 'Jerez'},
  {country: 'Indonesia', find: 'Jogja', replace: 'Yogyakarta'},
  {country: 'Indonesia', find: 'Jogjakarta', replace: 'Yogyakarta'},
  {country: 'France', find: 'Joinville Le Pont', replace: 'Joinville-le-Pont'},
  {country: 'India', find: 'Kchi', replace: 'Kochi'},
  {country: 'Ukraine', find: 'Kharkov', replace: 'Kharkiv'},
  {country: 'Thailand', find: 'Khonkaen', replace: 'Khon Kaen'},
  {country: 'Ukraine', find: 'Kiew', replace: 'Kyiv'},
  {country: 'United Kingdom', find: 'Kingston', replace: 'Kingston upon Thames'},
  {country: 'Hungaria', find: 'Kiskoros', replace: 'Kiskőrös'},
  {country: 'Ukraine', find: 'Kiyv', replace: 'Kyiv'},
  {country: 'Switzerland', find: 'Klignau', replace: 'Klingnau'},
  {country: 'Ukraine', find: 'Kyev', replace: 'Kyiv'},
  {country: 'Denmark', find: 'København ø', replace: 'Copenhagen'},
  {country: 'Spain', find: 'La Coruña', replace: 'A Coruña'},
  {country: 'France', find: 'La Ferté Sous Jouarre', replace: 'La Ferté-sous-Jouarre'},
  {country: 'France', find: 'La Fleche', replace: 'La Flèche'},
  {country: 'Spain', find: 'La Laguna', replace: 'San Cristóbal de La Laguna'},
  {country: 'France', find: 'La Roche Bernard', replace: 'La Roche-Bernard'},
  {country: 'France', find: 'La Roche Sur Yon', replace: 'La Roche-sur-Yon'},
  {country: 'France', find: 'La Teste', replace: 'La Teste-de-Buch'},
  {country: 'Honduras', find: 'Laceiba', replace: 'La Ceiba'},
  {country: 'Spain', find: 'Lanjaron', replace: 'Lanjarón'},
  {country: 'Spain', find: 'Las Palmas', replace: 'Las Palmas de Gran Canaria'},
  {country: 'Spain', find: 'Las Palmas De Gc', replace: 'Las Palmas de Gran Canaria'},
  {country: 'Spain', find: 'Las Palmas De Gran Canaria', replace: 'Las Palmas de Gran Canaria'},
  {country: 'France', find: 'Le Faux', replace: 'Lefaux'},
  {country: 'France', find: 'Le Perreux Sur Marne', replace: 'Le Perreux-sur-Marne'},
  {country: 'France', find: 'Le Puy-en-velay', replace: 'Le Puy'},
  {country: 'United Kingdom', find: 'Leamington Spa', replace: 'Royal Leamington Spa'},
  {country: 'Germany', find: 'Leipzsch', replace: 'Leipzig'},
  {country: 'Spain', find: 'Leon', replace: 'León'},
  {country: 'France', find: "Les Sables D'olonne", replace: "Les Sables-d'Olonne"},
  {country: 'Germany', find: 'Lheim', replace: 'Talheim'},
  {country: 'Germany', find: 'Lof', replace: 'Löf'},
  {country: 'United Kingdom', find: 'Londo N', replace: 'London'},
  {country: 'United Kingdom', find: 'London, Greater London', replace: 'London'},
  {country: 'United Kingdom', find: 'Londra', replace: 'London'},
  {country: 'Germany', find: 'Ludwigshafen Am Rhein', replace: 'Ludwigshafen'},
  {country: 'Ukraine', find: 'Lugansk', replace: 'Luhansk'},
  {country: 'Switzerland', find: 'Luzern', replace: 'Lucerne'},
  {country: 'Ukraine', find: 'Lvov', replace: 'Lviv'},
  {country: 'United Kingdom', find: 'Lyme', replace: 'Lyme Regis'},
  {country: 'France', find: 'Lys Lez Lannoy', replace: 'Lys-lez-Lannoy'},
  {country: 'Germany', find: 'Lörrac', replace: 'Lörrach'},
  {country: 'Spain', find: 'Mad', replace: 'Madrid'},
  {country: 'Turkey', find: 'Madin', replace: 'Mardin'},
  {country: 'Sweden', find: 'Malmo', replace: 'Malmö'},
  {country: 'United Kingdom', find: 'Man', replace: 'Manchester'},
  {country: 'United Kingdom', find: 'Manchaster', replace: 'Manchester'},
  {country: 'Ireland', find: 'Manchester', replace: 'Manchester Township'},
  {country: 'Finland', find: 'Manse', replace: 'Tampere'},
  {country: 'Macau', find: 'Mexico', replace: 'Aguascalientes'},
  {country: 'France', find: 'Marcq En Baroeul', replace: 'Marcq-en-Barœul'},
  {country: 'Spain', find: 'Marin', replace: 'Marín'},
  {country: 'Ukraine', find: 'Mariupol', replace: 'Mariupol'},
  {country: 'Tunisia', find: 'Marsa', replace: 'La Marsa'},
  {country: 'France', find: 'Marsiglia', replace: 'Marseille'},
  {country: 'Switzerland', find: 'Martigny-croix', replace: 'Martigny-Combe'},
  {country: 'Mexico', find: 'Matalvaro', replace: 'Álvaro'},
  {country: 'Germany', find: 'Md', replace: 'Magdeburg'},
  {country: 'Indonesia', find: 'Medan-indonesia', replace: 'Medan'},
  {country: 'Germany', find: 'Meerbuwch', replace: 'Meerbusch'},
  {country: 'Spain', find: 'Miranda De Ebro', replace: 'Miranda de Ebro'},
  {country: 'Germany', find: 'Moenchengladbach', replace: 'Mönchengladbach'},
  {country: 'France', find: 'Mont De Marsan', replace: 'Mont-de-Marsan'},
  {country: 'France', find: 'Montfort En Chalosse', replace: 'Montfort-en-Chalosse'},
  {country: 'France', find: 'Montreal', replace: 'Montréal'},
  {country: 'Spain', find: 'Moro Jable', replace: 'Morro Jable'},
  {country: 'Germany', find: 'Muelheim An Der Ruhr', replace: 'Mülheim'},
  {country: 'Germany', find: 'Muenchen', replace: 'Munich'},
  {country: 'Germany', find: 'München', replace: 'Munich'},
  {country: 'Russia', find: 'Nadum', replace: 'Nadym'},
  {country: 'Greece', find: 'Naoussa', replace: 'Naousa'},
  {country: 'Germany', find: 'Nbg', replace: 'Burglengenfeld'},
  {country: 'Germany', find: 'Near Düsseldorf', replace: 'Düsseldorf'},
  {country: 'Switzerland', find: 'Neuchatel', replace: 'Neuchâtel'},
  {country: 'France', find: 'Neuilly', replace: 'Neuilly-sur-Seine'},
  {country: 'France', find: 'Neuville-les-this', replace: 'Neuville-lès-This'},
  {country: 'United Kingdom', find: 'Newcastle', replace: 'Newcastle upon Tyne'},
  {country: 'United Kingdom', find: 'Newcastle Upon Tyne', replace: 'Newcastle upon Tyne'},
  {country: 'United Kingdom', find: 'Newcstle Upon Tyne', replace: 'Newcastle upon Tyne'},
  {country: 'Germany', find: 'Newhof', replace: 'Neuhof'},
  {country: 'Hong Kong', find: 'Newtown Square', replace: 'Kennett Square'},
  {country: 'France', find: 'Noisy Le Grand', replace: 'Noisy-le-Grand'},
  {country: 'Sweden', find: 'Nollberga', replace: 'Gillberga'},
  {country: 'United States', find: 'North Fond Du Lac', replace: 'North Fond du Lac'},
  {country: 'United Kingdom', find: 'Nottinghm', replace: 'Nottingham'},
  {country: 'United Kingdom', find: 'Nottinham', replace: 'Nottingham'},
  {country: 'Germany', find: 'Nu-ulm', replace: 'Neu-Ulm'},
  {country: 'Germany', find: 'Nueremberg', replace: 'Nuremberg'},
  {country: 'Germany', find: 'Nuernberg', replace: 'Nuremberg'},
  {country: 'Germany', find: 'Nuertingen', replace: 'Nürtingen'},
  {country: 'France', find: 'Nîmes', replace: 'Nimes'},
  {country: 'Germany', find: 'Nürnberg', replace: 'Nuremberg'},
  {country: 'Germany', find: 'N�rnberg', replace: 'Altdorf bei Nürnberg'},
  {country: 'Brazil', find: 'O Paulo', replace: 'São Paulo'},
  {country: 'Germany', find: 'Oltenburg', replace: 'Oldenburg'},
  {country: 'Spain', find: 'Orense', replace: 'Ourense'},
  {country: 'France', find: 'Orleans', replace: 'Orléans'},
  {country: 'Japan', find: 'Os', replace: 'Ōsaka-shi'},
  {country: 'France', find: 'Oui', replace: 'Paris'},
  {country: 'France', find: 'Pagny Sur Moselle', replace: 'Pagny-sur-Moselle'},
  {country: 'Thailand', find: 'Pakretnonthaburi', replace: 'Pak Kret'},
  {country: 'Spain', find: 'Palma De Malloca', replace: 'Palma'},
  {country: 'Spain', find: 'Palma De Mallorca', replace: 'Palma'},
  {country: 'Indonesia', find: 'Pangkalpinang', replace: 'Pangkal Pinang'},
  {country: 'Haiti', find: 'Pap', replace: 'Port-au-Prince'},
  {country: 'Suriname', find: 'Parbo', replace: 'Paramaribo'},
  {country: 'France', find: 'Pari', replace: 'Paris'},
  {country: 'France', find: 'Parigi/nizza', replace: 'Puteaux'},
  {country: 'France', find: 'Paris (France)', replace: 'Paris'},
  {country: 'France', find: 'Paris/berlin', replace: 'Paris'},
  {country: 'France', find: 'Paris/orleans', replace: 'Orléans'},
  {country: 'Thailand', find: 'Patong Beach, Kathu', replace: 'Patong'},
  {country: 'Hungary', find: 'Pecs', replace: 'Pécs'},
  {country: 'Hungaria', find: 'Pecs', replace: 'Pécs'},
  {country: 'Spain', find: 'Pelao', replace: 'Pollo Pelao'},
  {country: 'France', find: 'Pelussin', replace: 'Pélussin'},
  {country: 'France', find: 'Perigueux', replace: 'Périgueux'},
  {country: 'France', find: 'Perpi', replace: 'Perpignan'},
  {country: 'France', find: 'Plelan Le Grand', replace: 'Plélan-le-Grand'},
  {country: 'France', find: 'Ploeuc Sur Lié', replace: 'Plœuc-sur-Lié'},
  {country: 'France', find: 'Plouzane', replace: 'Plouzané'},
  {country: 'India', find: 'Pondicherry', replace: 'Puducherry'},
  {country: 'France', find: 'Pont Ste Maxence', replace: 'Pont-Sainte-Maxence'},
  {country: 'Haiti', find: 'Port Au Prince', replace: 'Port-au-Prince'},
  {country: 'Trinidad and Tobago', find: 'Port Of Spain', replace: 'Port of Spain'},
  {country: 'Falkland Islands (Islas Malvinas)', find: 'Port Stanley', replace: 'Stanley'},
  {country: 'Italy', find: "Porto Sant'elpidio", replace: "Porto Sant'Elpidio"},
  {country: 'Trinidad and Tobago', find: 'Pos', replace: 'Port of Spain'},
  {country: 'Ukraine', find: 'Poznan', replace: 'Poznan'},
  {country: 'Ukraine', find: 'Pripyat', replace: "Pryp'yat"},
  {country: 'India', find: 'Puna', replace: 'Pune'},
  {country: 'France', find: 'Ravines Des Cabris', replace: 'Ravine des Cabris'},
  {country: 'Iceland', find: 'Reykjavik', replace: 'Reykjavík'},
  {country: 'Germany', find: 'Ruesselsheim', replace: 'Rüsselsheim'},
  {country: 'Iceland', find: 'Rvk', replace: 'Reykjavík'},
  {country: 'Spain', find: 'S/c De Tenerife', replace: 'Santa Cruz de Tenerife'},
  {country: 'Germany', find: 'Saarbruecken', replace: 'Saarbrücken'},
  {country: 'France', find: 'Saigon', replace: 'Saignon'},
  {country: 'France', find: 'Saint Etienne', replace: 'Saint-Étienne'},
  {country: 'France', find: 'Saint Fargeau Ponthierry', replace: 'Saint-Fargeau-Ponthierry'},
  {country: 'France', find: 'Saint Laurent Du Var', replace: 'St-Laurent-du-Var'},
  {country: 'France', find: 'Saint Leu La Foret', replace: 'Saint-Leu-la-Forêt'},
  {country: 'France', find: 'Saint Marcel Sur Aude', replace: 'Saint-Marcel-sur-Aude'},
  {country: 'France', find: 'Saint Nicolas Les Citeaux', replace: 'Saint-Nicolas-lès-Cîteaux'},
  {country: 'France', find: 'Saint-amé', replace: 'Saint-Amé'},
  {country: 'France', find: 'Saint-denis', replace: 'Saint-Denis'},
  {country: 'France', find: 'Saint-denis De La Reunion', replace: 'Saint-Denis'},
  {country: 'France', find: 'Saint-etienne', replace: 'Saint-Étienne'},
  {country: 'France', find: 'Saint-lô', replace: 'Saint-Lô'},
  {country: 'France', find: 'Saint-maur', replace: 'Saint-Maur-des-Fossés'},
  {country: 'France', find: 'Saint-ouen', replace: 'Saint-Ouen'},
  {country: 'France', find: 'Saint-quentin', replace: 'Saint-Quentin'},
  {country: 'France', find: 'Saint-valery', replace: 'Saint-Valery-sur-Somme'},
  {country: 'Spain', find: 'Salaamanac', replace: 'Salamanca'},
  {country: 'France', find: 'Salon De Provence', replace: 'Salon-de-Provence'},
  {country: 'Greece', find: 'Salonico', replace: 'Thessaloniki'},
  {country: 'Greece', find: 'Salonika', replace: 'Thessaloniki'},
  {country: 'United Kingdom', find: 'Saltburn', replace: 'Saltburn-by-the-Sea'},
  {country: 'Spain', find: 'San Sebastian', replace: 'San Sebastián'},
  {country: 'Spain', find: 'San Sebatian', replace: 'San Sebastián'},
  {country: 'Italy', find: "Sant'ilario D'enza", replace: "Sant'Ilario d'Enza"},
  {country: 'Spain', find: 'Santa Cruz De Tenerife', replace: 'Santa Cruz de Tenerife'},
  {country: 'Spain', find: 'Santiago', replace: 'Santiago de Compostela'},
  {country: 'Spain', find: 'Santiago De Compostela', replace: 'Santiago de Compostela'},
  {country: 'Brazil', find: 'Santo âNgelo', replace: 'Santo Ângelo'},
  {country: 'Spain', find: 'Santurce', replace: 'Santurtzi'},
  {country: 'Spain', find: 'Saragozza', replace: 'Zaragoza'},
  {country: 'France', find: 'Sarlat', replace: 'Sarlat-la-Canéda'},
  {country: 'Germany', find: 'Schwaebisch Hall', replace: 'Schwäbisch Hall'},
  {country: 'Germany', find: 'Schwenningen', replace: 'Villingen-Schwenningen'},
  {country: 'Hungary', find: 'Sd', replace: 'Budapest'},
  {country: 'Bosnia and Herzegovina', find: 'Sekovici', replace: 'Šekovići'},
  {country: 'Hungary', find: 'Siklos', replace: 'Siklós'},
  {country: 'United Arab Emirates', find: 'Silicon Oasis Dubai', replace: 'Dubai'},
  {country: 'Ukraine', find: 'Simferpool', replace: 'Simferopol'},
  {country: 'RU', find: 'Sob', replace: 'Sobra'},
  {country: 'Spain', find: 'South Chiclana', replace: 'Chiclana de la Frontera'},
  {country: 'France', find: 'Space', replace: 'Nice'},
  {country: 'Croatia', find: 'Spalato', replace: 'Split'},
  {country: 'Germany', find: 'Sseldorf', replace: 'Düsseldorf'},
  {country: 'France', find: 'St André', replace: 'Saint-André'},
  {country: 'France', find: 'St Brieuc', replace: 'Saint-Brieuc'},
  {country: 'France', find: 'St Denis', replace: 'Saint-Denis'},
  {country: 'France', find: 'St Denis, La Reunion', replace: 'Saint-Denis'},
  {country: 'United Kingdom', find: 'St Ives', replace: 'Saint Ives'},
  {country: 'Spain', find: 'St. Sebastian', replace: 'San Sebastián'},
  {country: 'France', find: 'St_rambert', replace: 'Saint-Rambert-en-Bugey'},
  {country: 'Turkey', find: 'Stbnul', replace: 'Istanbul'},
  {country: 'Germany', find: 'Steinbach-hallenberg', replace: 'Steinbach-Hallenberg'},
  {country: 'Sweden', find: 'Sterås', replace: 'Västerås'},
  {country: 'Sweden', find: 'Sthlm', replace: 'Stockholm'},
  {country: 'Indonesia', find: 'Surabya', replace: 'Surabaya'},
  {country: 'Thailand', find: 'Suratthani', replace: 'Surat Thani'},
  {country: 'Hungary', find: 'Szekszard', replace: 'Szekszárd'},
  {country: 'Hungary', find: 'Szexhard', replace: 'Szekszárd'},
  {country: 'Hungary', find: 'Szigetszentmikós', replace: 'Szigetszentmiklós'},
  {country: 'Poland', find: 'Słupsk', replace: 'Slupsk'},
  {country: 'IL', find: 'Tel Aviv', replace: 'Tel Aviv-Yafo'},
  {country: 'France', find: 'Tolosa', replace: 'Toulouse'},
  {country: 'France', find: 'Toulours', replace: 'Toulouse'},
  {country: 'Vietnam', find: 'Tphcm', replace: 'Ho Chi Minh City'},
  {country: 'France', find: 'Trelissac', replace: 'Trélissac'},
  {country: 'India', find: 'Trivandrum', replace: 'Thiruvananthapuram'},
  {country: 'Spain', find: 'Trobajo Del Camino', replace: 'Trobajo del Camino'},
  {country: 'Ukraine', find: 'Tschernobyl', replace: 'Chornobyl'},
  {country: 'France', find: 'Tt', replace: 'Tourves'},
  {country: 'India', find: 'Tuticorin', replace: 'Thoothukudi'},
  {country: 'India', find: 'Tutukurin', replace: 'Thoothukudi'},
  {country: 'Mexico', find: 'Tzcuaro', replace: 'Pátzcuaro'},
  {country: 'Hungary', find: 'Tàpiószele', replace: 'Tápiószele'},
  {country: 'Germany', find: 'Ulma', replace: 'Ulm'},
  {country: 'Turkey', find: 'Urfa', replace: 'Şanlıurfa'},
  {country: 'Spain', find: 'Valderrobres(teruel)', replace: 'Valderrobres'},
  {country: 'Spain', find: 'Valencia-palermo', replace: 'Valencia'},
  {country: 'Sweden', find: 'Vargarda', replace: 'Vårgårda'},
  {country: 'France', find: "Vern D'anjou", replace: "Vern-d'Anjou"},
  {country: 'Greece', find: 'Veroia', replace: 'Veria'},
  {country: 'Spain', find: 'Vilafranca De Bonany', replace: 'Vilafranca de Bonany'},
  {country: 'Spain', find: 'Vilafranca Del Penedès', replace: 'Vilafranca del Penedès'},
  {country: 'Spain', find: 'Vilanova I La Geltru', replace: 'Vilanova i la Geltrú'},
  {country: 'Spain', find: 'Vilanova I La Geltrú', replace: 'Vilanova i la Geltrú'},
  {country: 'Germany', find: 'Villingen', replace: 'Villingen-Schwenningen'},
  {country: 'Germany', find: 'Weil', replace: 'Weil am Rhein'},
  {country: 'Germany', find: 'Weissenfels', replace: 'Weißenfels'},
  {country: 'India', find: 'Vizag', replace: 'Visakhapatnam'},
  {country: 'Indonesia', find: 'Yogya', replace: 'Yogyakarta'},
  {country: 'Switzerland', find: 'Yverdon', replace: 'Yverdon-les-Bains'},
  {country: 'Switzerland', find: 'Zuerich', replace: 'Zürich'},
  {country: 'Switzerland', find: 'Zuricgo', replace: 'Zürich'},
  {country: 'Switzerland', find: 'Zurich', replace: 'Zürich'},
  {country: 'Norway', find: 'åLesund', replace: 'Alesund'},
  {country: 'Turkey', find: 'çOrum', replace: 'Çorum'},
  {country: 'Greece', find: 'αθήνα', replace: 'Athens'},
  {country: 'Greece', find: 'αθηνα', replace: 'Athens'},
  {country: 'Greece', find: 'δοξάτο', replace: 'Doxato'},
  {country: 'Turkmenistan', find: 'ашхабад', replace: 'Ashgabat'},
  {country: 'Russia', find: 'благовєщенск', replace: 'Blagoveshchensk'},
  {country: 'Russia', find: 'екатєринбург', replace: 'Yekaterinburg'},
  {country: 'Ukraine', find: 'житомир', replace: 'Zhytomyr'},
  {country: 'Russia', find: 'йошкар-ола', replace: 'Yoshkar-Ola'},
  {country: 'Ukraine', find: 'києв', replace: 'Kyiv'},
  {country: 'Russia', find: 'новосибирск', replace: 'Novosibirsk'},
  {country: 'Russia', find: 'норильск', replace: 'Norilsk'},
  {country: 'Russia', find: 'санкт-пєтербург', replace: 'Saint Petersburg'},
  {country: 'Russia', find: 'саранск', replace: 'Saransk'},
  {country: 'Russia', find: 'туапсє', replace: 'Tuapse'},
  {country: 'Ukraine', find: 'харьков', replace: 'Kharkiv'},
  {country: 'China', find: '南京', replace: 'Nanjing'},
  {country: 'China', find: '厦门', replace: 'Xiamen'},
  {country: 'China', find: '嘉兴', replace: 'Jiaxing'},
  {country: 'China', find: '太原', replace: 'Taiyuan'},
  {country: 'China', find: '成都', replace: 'Chengdu'},
  {country: 'Japan', find: '春日部市', replace: 'Kasukabe'},
  {country: 'China', find: '武汉', replace: 'Wuhan'},
  {country: 'China', find: '汕头', replace: 'Shantou'},
  {country: 'China', find: '沈阳', replace: 'Shenyang'},
  {country: 'China', find: '浙江绍兴', replace: 'Shaoxing'},
  {country: 'China', find: '温州', replace: 'Wenzhou'},
  {country: 'China', find: '襄阳', replace: 'Xiangyang'},
  {country: 'China', find: '西安', replace: "Xi'an"},
  {country: 'China', find: '辽宁沈阳', replace: 'Shenyang'}
];