const PREFIX = 'ACTIVITIES_';

export const SAVE_MODEL_SUCCESS = PREFIX + 'SAVE_MODEL_SUCCESS';
export const SAVE_MODEL_ERROR = PREFIX + 'SAVE_MODEL_ERROR';
export const SAVE_MODEL_REQUEST = PREFIX + 'SAVE_MODEL_REQUEST';
