export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

export const MODAL_EXAMPLE = "MODAL_EXAMPLE";
export const MODAL_REMOVE = "MODAL_REMOVE";
export const MODAL_SAVED = "MODAL_SAVED";
export const MODAL_ADD_EVENT = "MODAL_ADD_EVENT";

export const MODAL_ADD_PERFORMANCE = "MODAL_ADD_PERFORMANCE";

export const MODAL_ADD_USER_PERFORMANCE = "MODAL_ADD_USER_PERFORMANCE";

export const MODAL_ADD_USER_EVENT = "MODAL_ADD_USER_EVENT";

export const MODAL_ADD_USER_VIDEOS = "MODAL_ADD_USER_VIDEOS";

export const MODAL_ADD_USER_GALLERIES = "MODAL_ADD_USER_GALLERIES";

export const MODAL_ADD_USER_FOOTAGE = "MODAL_ADD_USER_FOOTAGE";

export const MODAL_ADD_USER_NEWS = "MODAL_ADD_USER_NEWS";

export const MODAL_ADD_USER_PLAYLISTS = "MODAL_ADD_USER_PLAYLISTS";

export const MODAL_ADD_MEDIA = "MODAL_ADD_MEDIA";

export const MODAL_ADD_PARTNER = "MODAL_ADD_PARTNER";

export const MODAL_ADD_CREW = "MODAL_ADD_CREW";

export const MODAL_ADD_MEMBERS = "MODAL_ADD_MEMBERS";

export const MODAL_ADD_FOOTAGE = "MODAL_ADD_FOOTAGE";

export const MODAL_ADD_NEWS = "MODAL_ADD_NEWS";

export const MODAL_ADD_PLAYLIST = "MODAL_ADD_PLAYLIST";

export const MODAL_ADD_VIDEOS = "MODAL_ADD_VIDEOS";

export const MODAL_ADD_GALLERIES = "MODAL_ADD_GALLERIES";

export const MODAL_SIGN_UP_SUCCESS = "MODAL_SIGN_UP_SUCCESS";

export const MODAL_ADD_PERFORMANCES_GALLERIES =
  "MODAL_ADD_PERFORMANCES_GALLERIES";

export const MODAL_ADD_PERFORMANCES_VIDEOS = "MODAL_ADD_PERFORMANCES_VIDEOS";

export const MODAL_ADD_EVENTS_GALLERIES = "MODAL_ADD_EVENTS_GALLERIES";

export const MODAL_ADD_EVENTS_VIDEOS = "MODAL_ADD_EVENTS_VIDEOS";

export const MODAL_EMAIL_VERIFICATION_SUCCESS =
  "MODAL_EMAIL_VERIFICATION_SUCCESS";
export const MODAL_EMAIL_VERIFICATION_ERROR = "MODAL_EMAIL_VERIFICATION_ERROR";
