export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

export const MODAL_EXAMPLE = "MODAL_EXAMPLE";
export const MODAL_REMOVE = "MODAL_REMOVE";
export const MODAL_SAVED = "MODAL_SAVED";
export const MODAL_ADD_EVENT = "MODAL_ADD_EVENT";

export const MODAL_ADD_PERFORMANCE = "MODAL_ADD_PERFORMANCE";
export const MODAL_ADD_USER_PERFORMANCE = "MODAL_ADD_USER_PERFORMANCE";

export const MODAL_ADD_MEDIA = "MODAL_ADD_MEDIA";

export const MODAL_ADD_PARTNER = "MODAL_ADD_PARTNER";

export const MODAL_ADD_CREW = "MODAL_ADD_CREW";

export const MODAL_ADD_MEMBERS = "MODAL_ADD_MEMBERS";

export const MODAL_ADD_FOOTAGE = "MODAL_ADD_FOOTAGE";