const PREFIX = 'PERFORMANCES_';
export const MODELS_NAME = "performances";

export const FETCH_LIST_SUCCESS = PREFIX + 'FETCH_LIST_SUCCESS';
export const FETCH_LIST_ERROR = PREFIX + 'FETCH_LIST_ERROR';
export const FETCH_LIST_REQUEST = PREFIX + 'FETCH_LIST_REQUEST';

export const FETCH_MODEL_SUCCESS = PREFIX + 'FETCH_MODEL_SUCCESS';
export const FETCH_MODEL_ERROR = PREFIX + 'FETCH_MODEL_ERROR';
export const FETCH_MODEL_REQUEST = PREFIX + 'FETCH_MODEL_REQUEST';

export const SAVE_MODEL_REQUEST = PREFIX + "SAVE_MODEL_REQUEST";
export const SAVE_MODEL_SUCCESS = PREFIX + "SAVE_MODEL_SUCCESS";
export const SAVE_MODEL_ERROR = PREFIX + "SAVE_MODEL_ERROR";

export const FETCH_USERS_SUCCESS = PREFIX + 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = PREFIX + 'FETCH_USERS_ERROR';
export const FETCH_USERS_REQUEST = PREFIX + 'FETCH_USERS_REQUEST';
