export const FORM_NAME = "NEWS.USERS";

const PREFIX = "USERS_";
export const MODELS_NAME = "users";

export const FETCH_LIST_SUCCESS = PREFIX + "FETCH_LIST_SUCCESS";
export const FETCH_LIST_ERROR = PREFIX + "FETCH_LIST_ERROR";
export const FETCH_LIST_REQUEST = PREFIX + "FETCH_LIST_REQUEST";
